name: Build AMD64 MUSL

on:
  workflow_dispatch:

jobs:
  amd64_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Make
      run: |
        docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp amd64/gcc bash -c "wget https://git.musl-libc.org/cgit/musl/snapshot/musl-1.2.4.tar.gz && tar -zxvf musl-1.2.4.tar.gz && cd musl-1.2.4 && ./configure && make && make install && cd .. && sed -i 's/patch.*static-glibc-nginx.patch/:/g' ./Makefile && sed -i 's#\\\$(CC)#/usr/local/musl/bin/musl-gcc#g' ./Makefile && make"

    - uses: actions/upload-artifact@v3
      with:
        name: nginx_amd64
        path: nginx/nginx
