name: Makefile Linux x86_64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make
      run: make

    - uses: actions/upload-artifact@v3
      with:
        name: nginx
        path: nginx
